export let tasks = [
    {
        id: 1,
        title: "Design REST API Endpoints",
        desc: "Plan GET, POST, PUT, DELETE for /tasks route.",
        category: "Development",
        sprint: "2026-W42",
        date: "2026-05-31",
        time: "09:30",
        duration: "3",
        energy: 5,
        url: "https://yosong.dev",
        color: "#334155",
        completed: false,
        status: "active",
    },
    {
        id: 2,
        title: "30 Min Jogging in the Park",
        desc: "Clear the mind before coding.",
        category: "Health & Routine",
        sprint: "",
        date: "2026-05-31",
        time: "05:30",
        duration: "0.5",
        energy: 3,
        url: "",
        color: "#10b981",
        completed: true,
        status: "active",
    },
    {
        id: 3,
        title: "Implement JWT Authentication",
        desc: "Setup login, register, and protected routes using JSON Web Tokens. Handle edge cases.",
        category: "Development",
        sprint: "2026-W42",
        date: "2026-06-01",
        time: "13:00",
        duration: "4",
        energy: 5,
        url: "",
        color: "#eab308",
        completed: false,
        status: "active",
    },
    {
        id: 4,
        title: "Book Omakase Sushi Dinner",
        desc: "Call the restaurant to reserve a seat for Friday night reward.",
        category: "Health & Routine",
        sprint: "",
        date: "2026-06-05",
        time: "18:00",
        duration: "1",
        energy: 1,
        url: "",
        color: "#a3e635",
        completed: false,
        status: "active",
    },
    {
        id: 5,
        title: "Draft Wireframes on Figma",
        desc: "Initial layout for Balance Tracker.",
        category: "Development",
        sprint: "2026-W41",
        date: "2026-06-01",
        time: "14:00",
        duration: "2",
        energy: 3,
        url: "https://figma.com",
        color: "#ec4899",
        completed: true,
        status: "archived",
    },
];
